### ISSUE TITLE
Configuration not saved for my.openHAB.org

### ISSUE THREAD

**Issue by perrin7** [openhab/openhab.pebble#1]
working configuration settings:
Local: http://openhab.local:8080
sitemap: pebble
rest of the options: blank

attempt to add in remote connection:
Local: http://openhab.local:8080
Remote: https://my.openhab.org/
Username: myemailaddress@gmail.com
Password: myOpenHABpassword
sitemap: pebble

After clicking "Submit" the form closes and reverts to "local only" configuration options.
##

**Comment by llamahunter** [comment]
What brand and model of phone do you have?

**Comment by perrin7** [comment]
Samsung Note 3, running Cyanogenmod 12.1 (Android 5.1.1)

**Comment by llamahunter** [comment]
Hmm.. It's possible there's something weird about how the pebble app runs the embedded web browser on Android.  It's pretty standard looking code, and I lifted it straight from the pebbledev people.  Do you have the ability to get pebble logs from your phone?  Easiest way is to build the app yourself using cloudpebble and deploy it to your watch using developer mode.

**Comment by perrin7** [comment]
OK - did some more digging.

I can get all the settings in if I do them one at a time - but as soon as I try to put the password field in, it crashes out and doesn't save. 

```
LOG FILE

[PHONE] pebble-app.js:?: {'runhost client uuid' = 00000000-0000-0000-0000-000000000000}:{'webapp uuid' = 73ad05b2-2f62-4f57-934a-0f820530f401}: ++_JS_LIFECYCLE_++:LAUNCHING
[PHONE] pebble-app.js:?: OpenHAB_for_Pebble__1.0/pebble-js-app.js:5818 (+) [window 1] : [window 1]
[PHONE] pebble-app.js:?: OpenHAB_for_Pebble__1.0/pebble-js-app.js:5908 29/9/2015 8:32:22 am: starting up
[PHONE] pebble-app.js:?: {'runhost client uuid' = 3c021db4-e2e4-47c6-90b3-f5f3ebd26758}:{'webapp uuid' = 73ad05b2-2f62-4f57-934a-0f820530f401}: ++_JS_LIFECYCLE_++:READY-RUNNING
[PHONE] pebble-app.js:?: OpenHAB_for_Pebble__1.0/pebble-js-app.js:5908 29/9/2015 8:32:22 am: Failed to fetch sitemaps: 
[PHONE] pebble-app.js:?: OpenHAB_for_Pebble__1.0/pebble-js-app.js:5818 (+) [card 2] : [window 1],[card 2]
[PHONE] pebble-app.js:?: OpenHAB_for_Pebble__1.0/pebble-js-app.js:5839 (-) [window 1] : [card 2]
[PHONE] pebble-app.js:?: {'runhost client uuid' = 2923a68a-656c-4c53-a9d4-beb03b92e72c}:{'webapp uuid' = 2923a68a-656c-4c53-a9d4-beb03b92e72c}: ++_JS_LIFECYCLE_++:KILLED
[PHONE] pebble-app.js:?: {'runhost client uuid' = 2923a68a-656c-4c53-a9d4-beb03b92e72c}:{'webapp uuid' = 2923a68a-656c-4c53-a9d4-beb03b92e72c}: ++_JS_LIFECYCLE_++:KILLED
[PHONE] pebble-app.js:?: OpenHAB_for_Pebble__1.0/pebble-js-app.js:5908 29/9/2015 8:32:53 am: Configuration window returned: {"localUrl":"http://openhab.local:8080","remoteUrl":"Https://my.openhab.org","username":"","password":"","sitemap":"pebble"}
[PHONE] pebble-app.js:?: OpenHAB_for_Pebble__1.0/pebble-js-app.js:5908 29/9/2015 8:32:53 am: config changed
[PHONE] pebble-app.js:?: OpenHAB_for_Pebble__1.0/pebble-js-app.js:5818 (+) [window 1] : [card 2],[window 1]
[PHONE] pebble-app.js:?: OpenHAB_for_Pebble__1.0/pebble-js-app.js:1040 jskit_startup.js:203:25
[PHONE] pebble-app.js:?: OpenHAB_for_Pebble__1.0/pebble-js-app.js:1040 jskit_startup.js:121:50
[PHONE] pebble-app.js:?: OpenHAB_for_Pebble__1.0/pebble-js-app.js:1040 lib/safe.js:140:17
[PHONE] pebble-app.js:?: OpenHAB_for_Pebble__1.0/pebble-js-app.js:1040 settings/settings.js:205:23
[PHONE] pebble-app.js:?: OpenHAB_for_Pebble__1.0/pebble-js-app.js:1040 config.js:85:15
[PHONE] pebble-app.js:?: OpenHAB_for_Pebble__1.0/pebble-js-app.js:1040 app.js:26:13
[PHONE] pebble-app.js:?: OpenHAB_for_Pebble__1.0/pebble-js-app.js:1040 windowmgr.js:42:12
[PHONE] pebble-app.js:?: OpenHAB_for_Pebble__1.0/pebble-js-app.js:1083 JavaScript Error:
TypeError: undefined is not a function
    at Object.exports.popAll (windowmgr.js:42:12)
    at Object.Config.onConfigChanged (app.js:26:13)
    at Object.close (config.js:85:15)
    at Array.Settings.onCloseConfig (settings/settings.js:205:23)
    at Array.<anonymous> (lib/safe.js:140:17)
    at Object.PebbleEventListener.dispatchEvent (jskit_startup.js:121:50)
    at signalWebviewClosedEvent (jskit_startup.js:203:25)
    at <anonymous>:1:1
[PHONE] pebble-app.js:?: {'runhost client uuid' = b3f1d881-afa1-4b16-a6a0-df127e36eb83}:{'webapp uuid' = b3f1d881-afa1-4b16-a6a0-df127e36eb83}: ++_JS_LIFECYCLE_++:KILLED
[PHONE] pebble-app.js:?: {'runhost client uuid' = b3f1d881-afa1-4b16-a6a0-df127e36eb83}:{'webapp uuid' = b3f1d881-afa1-4b16-a6a0-df127e36eb83}: ++_JS_LIFECYCLE_++:KILLED
[PHONE] pebble-app.js:?: OpenHAB_for_Pebble__1.0/pebble-js-app.js:5908 29/9/2015 8:33:17 am: Configuration window returned: {"localUrl":"http://openhab.local:8080","remoteUrl":"Https://my.openhab.org","username":"my.email.address@gmail.com","password":"","sitemap":"pebble"}
[PHONE] pebble-app.js:?: OpenHAB_for_Pebble__1.0/pebble-js-app.js:5908 29/9/2015 8:33:17 am: config changed
[PHONE] pebble-app.js:?: OpenHAB_for_Pebble__1.0/pebble-js-app.js:1040 jskit_startup.js:203:25
[PHONE] pebble-app.js:?: OpenHAB_for_Pebble__1.0/pebble-js-app.js:1040 jskit_startup.js:121:50
[PHONE] pebble-app.js:?: OpenHAB_for_Pebble__1.0/pebble-js-app.js:1040 lib/safe.js:140:17
[PHONE] pebble-app.js:?: OpenHAB_for_Pebble__1.0/pebble-js-app.js:1040 settings/settings.js:205:23
[PHONE] pebble-app.js:?: OpenHAB_for_Pebble__1.0/pebble-js-app.js:1040 config.js:85:15
[PHONE] pebble-app.js:?: OpenHAB_for_Pebble__1.0/pebble-js-app.js:1040 app.js:26:13
[PHONE] pebble-app.js:?: OpenHAB_for_Pebble__1.0/pebble-js-app.js:1040 windowmgr.js:42:12
[PHONE] pebble-app.js:?: OpenHAB_for_Pebble__1.0/pebble-js-app.js:1083 JavaScript Error:
TypeError: undefined is not a function
    at Object.exports.popAll (windowmgr.js:42:12)
    at Object.Config.onConfigChanged (app.js:26:13)
    at Object.close (config.js:85:15)
    at Array.Settings.onCloseConfig (settings/settings.js:205:23)
    at Array.<anonymous> (lib/safe.js:140:17)
    at Object.PebbleEventListener.dispatchEvent (jskit_startup.js:121:50)
    at signalWebviewClosedEvent (jskit_startup.js:203:25)
    at <anonymous>:1:1
[PHONE] pebble-app.js:?: {'runhost client uuid' = d3393e17-903c-45e7-a08a-a156cd5253b5}:{'webapp uuid' = d3393e17-903c-45e7-a08a-a156cd5253b5}: ++_JS_LIFECYCLE_++:KILLED
[PHONE] pebble-app.js:?: {'runhost client uuid' = 5f9d3c77-d733-435a-9ead-32155f06903a}:{'webapp uuid' = 5f9d3c77-d733-435a-9ead-32155f06903a}: ++_JS_LIFECYCLE_++:KILLED
[PHONE] pebble-app.js:?: {'runhost client uuid' = 5f9d3c77-d733-435a-9ead-32155f06903a}:{'webapp uuid' = 5f9d3c77-d733-435a-9ead-32155f06903a}: ++_JS_LIFECYCLE_++:KILLED
[PHONE] pebble-app.js:?: OpenHAB_for_Pebble__1.0/pebble-js-app.js:1040 jskit_startup.js:203:25
[PHONE] pebble-app.js:?: OpenHAB_for_Pebble__1.0/pebble-js-app.js:1040 jskit_startup.js:121:50
[PHONE] pebble-app.js:?: OpenHAB_for_Pebble__1.0/pebble-js-app.js:1040 lib/safe.js:140:17
[PHONE] pebble-app.js:?: OpenHAB_for_Pebble__1.0/pebble-js-app.js:1040 settings/settings.js:178:45
[PHONE] pebble-app.js:?: OpenHAB_for_Pebble__1.0/pebble-js-app.js:1040 settings/settings.js:178:45
[PHONE] pebble-app.js:?: OpenHAB_for_Pebble__1.0/pebble-js-app.js:1083 JavaScript Error:
URIError: URI malformed
    at decodeURIComponent (settings/settings.js:178:45)
    at Array.Settings.onCloseConfig (settings/settings.js:178:45)
    at Array.<anonymous> (lib/safe.js:140:17)
    at Object.PebbleEventListener.dispatchEvent (jskit_startup.js:121:50)
    at signalWebviewClosedEvent (jskit_startup.js:203:25)
    at <anonymous>:1:1
[PHONE] pebble-app.js:?: {'runhost client uuid' = f86abc88-323a-4353-a52f-6064712143f6}:{'webapp uuid' = f86abc88-323a-4353-a52f-6064712143f6}: ++_JS_LIFECYCLE_++:KILLED
[PHONE] pebble-app.js:?: {'runhost client uuid' = f86abc88-323a-4353-a52f-6064712143f6}:{'webapp uuid' = f86abc88-323a-4353-a52f-6064712143f6}: ++_JS_LIFECYCLE_++:KILLED
[PHONE] pebble-app.js:?: OpenHAB_for_Pebble__1.0/pebble-js-app.js:1040 jskit_startup.js:203:25
[PHONE] pebble-app.js:?: OpenHAB_for_Pebble__1.0/pebble-js-app.js:1040 jskit_startup.js:121:50
[PHONE] pebble-app.js:?: OpenHAB_for_Pebble__1.0/pebble-js-app.js:1040 lib/safe.js:140:17
[PHONE] pebble-app.js:?: OpenHAB_for_Pebble__1.0/pebble-js-app.js:1040 settings/settings.js:178:45
[PHONE] pebble-app.js:?: OpenHAB_for_Pebble__1.0/pebble-js-app.js:1040 settings/settings.js:178:45
[PHONE] pebble-app.js:?: OpenHAB_for_Pebble__1.0/pebble-js-app.js:1083 JavaScript Error:
URIError: URI malformed
    at decodeURIComponent (settings/settings.js:178:45)
    at Array.Settings.onCloseConfig (settings/settings.js:178:45)
    at Array.<anonymous> (lib/safe.js:140:17)
    at Object.PebbleEventListener.dispatchEvent (jskit_startup.js:121:50)
    at signalWebviewClosedEvent (jskit_startup.js:203:25)
    at <anonymous>:1:1

[PHONE] pebble-app.js:?: {'runhost client uuid' = 6ef6b6d4-26dd-4374-8339-2e0a8a5c9ebc}:{'webapp uuid' = 6ef6b6d4-26dd-4374-8339-2e0a8a5c9ebc}: ++_JS_LIFECYCLE_++:KILLED
[PHONE] pebble-app.js:?: {'runhost client uuid' = 6ef6b6d4-26dd-4374-8339-2e0a8a5c9ebc}:{'webapp uuid' = 6ef6b6d4-26dd-4374-8339-2e0a8a5c9ebc}: ++_JS_LIFECYCLE_++:KILLED
[PHONE] pebble-app.js:?: OpenHAB_for_Pebble__1.0/pebble-js-app.js:5908 29/9/2015 8:35:56 am: Configuration window returned: {"localUrl":"http://openhab.local:8080","remoteUrl":"Https://my.openhab.org/test ","username":"my.email.address@gmail.com","password":"","sitemap":"pebble"}
[PHONE] pebble-app.js:?: OpenHAB_for_Pebble__1.0/pebble-js-app.js:5908 29/9/2015 8:35:56 am: config changed
[PHONE] pebble-app.js:?: OpenHAB_for_Pebble__1.0/pebble-js-app.js:1040 jskit_startup.js:203:25
[PHONE] pebble-app.js:?: OpenHAB_for_Pebble__1.0/pebble-js-app.js:1040 jskit_startup.js:121:50
[PHONE] pebble-app.js:?: OpenHAB_for_Pebble__1.0/pebble-js-app.js:1040 lib/safe.js:140:17
[PHONE] pebble-app.js:?: OpenHAB_for_Pebble__1.0/pebble-js-app.js:1040 settings/settings.js:205:23
[PHONE] pebble-app.js:?: OpenHAB_for_Pebble__1.0/pebble-js-app.js:1040 config.js:85:15
[PHONE] pebble-app.js:?: OpenHAB_for_Pebble__1.0/pebble-js-app.js:1040 app.js:26:13
[PHONE] pebble-app.js:?: OpenHAB_for_Pebble__1.0/pebble-js-app.js:1040 windowmgr.js:42:12
[PHONE] pebble-app.js:?: OpenHAB_for_Pebble__1.0/pebble-js-app.js:1083 JavaScript Error:
TypeError: undefined is not a function
    at Object.exports.popAll (windowmgr.js:42:12)
    at Object.Config.onConfigChanged (app.js:26:13)
    at Object.close (config.js:85:15)
    at Array.Settings.onCloseConfig (settings/settings.js:205:23)
    at Array.<anonymous> (lib/safe.js:140:17)
    at Object.PebbleEventListener.dispatchEvent (jskit_startup.js:121:50)
    at signalWebviewClosedEvent (jskit_startup.js:203:25)
    at <anonymous>:1:1

[PHONE] pebble-app.js:?: {'runhost client uuid' = efe7981d-25b9-4ee7-9552-1c23e1bcbfc6}:{'webapp uuid' = efe7981d-25b9-4ee7-9552-1c23e1bcbfc6}: ++_JS_LIFECYCLE_++:KILLED
[PHONE] pebble-app.js:?: {'runhost client uuid' = efe7981d-25b9-4ee7-9552-1c23e1bcbfc6}:{'webapp uuid' = efe7981d-25b9-4ee7-9552-1c23e1bcbfc6}: ++_JS_LIFECYCLE_++:KILLED
[PHONE] pebble-app.js:?: OpenHAB_for_Pebble__1.0/pebble-js-app.js:5908 29/9/2015 8:36:25 am: Configuration window returned: {"localUrl":"http://openhab.local:8080","remoteUrl":"Https://my.openhab.org","username":"my.email.address@gmail.com","password":"tttttt","sitemap":"pebble"}
[PHONE] pebble-app.js:?: OpenHAB_for_Pebble__1.0/pebble-js-app.js:5908 29/9/2015 8:36:25 am: config changed
[PHONE] pebble-app.js:?: OpenHAB_for_Pebble__1.0/pebble-js-app.js:1040 jskit_startup.js:203:25
[PHONE] pebble-app.js:?: OpenHAB_for_Pebble__1.0/pebble-js-app.js:1040 jskit_startup.js:121:50
[PHONE] pebble-app.js:?: OpenHAB_for_Pebble__1.0/pebble-js-app.js:1040 lib/safe.js:140:17
[PHONE] pebble-app.js:?: OpenHAB_for_Pebble__1.0/pebble-js-app.js:1040 settings/settings.js:205:23
[PHONE] pebble-app.js:?: OpenHAB_for_Pebble__1.0/pebble-js-app.js:1040 config.js:85:15
[PHONE] pebble-app.js:?: OpenHAB_for_Pebble__1.0/pebble-js-app.js:1040 app.js:26:13
[PHONE] pebble-app.js:?: OpenHAB_for_Pebble__1.0/pebble-js-app.js:1040 windowmgr.js:42:12
[PHONE] pebble-app.js:?: OpenHAB_for_Pebble__1.0/pebble-js-app.js:1083 JavaScript Error:
TypeError: undefined is not a function
    at Object.exports.popAll (windowmgr.js:42:12)
    at Object.Config.onConfigChanged (app.js:26:13)
    at Object.close (config.js:85:15)
    at Array.Settings.onCloseConfig (settings/settings.js:205:23)
    at Array.<anonymous> (lib/safe.js:140:17)
    at Object.PebbleEventListener.dispatchEvent (jskit_startup.js:121:50)
    at signalWebviewClosedEvent (jskit_startup.js:203:25)
at <anonymous>:1:1
```

**Comment by llamahunter** [comment]
It like like a URL encoding exception is being thrown. Does the password you tried have URL unfriendly characters in it? It seems that you tried 'tttt' and it worked, no?

I believe it's just using a common URL encoding jquery library or maybe a browser provided one. It's possible the one it's using is buggy. Don't have access to the source code right now so can't easily check. 

Richard

**Comment by llamahunter** [comment]
I think this has been fixed by recent changes.  Please re-check.
